[2021-09-17 16:33:15,592]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.address`.
[2021-09-17 16:33:15,599]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.address` has been localized to `zh_CN`.
[2021-09-17 16:33:15,600]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.automotive`.
[2021-09-17 16:33:15,604]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.automotive`. Locale reset to `en_US` for this provider.
[2021-09-17 16:33:15,605]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.bank`.
[2021-09-17 16:33:15,609]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
[2021-09-17 16:33:15,609]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.barcode`.
[2021-09-17 16:33:15,610]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.barcode`. Locale reset to `en_US` for this provider.
[2021-09-17 16:33:15,612]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.color`.
[2021-09-17 16:33:15,615]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.color`. Locale reset to `en_US` for this provider.
[2021-09-17 16:33:15,615]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.company`.
[2021-09-17 16:33:15,620]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.company` has been localized to `zh_CN`.
[2021-09-17 16:33:15,621]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.credit_card`.
[2021-09-17 16:33:15,622]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.credit_card`. Locale reset to `en_US` for this provider.
[2021-09-17 16:33:15,622]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.currency`.
[2021-09-17 16:33:15,625]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.currency`. Locale reset to `en_US` for this provider.
[2021-09-17 16:33:15,626]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.date_time`.
[2021-09-17 16:33:15,630]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.date_time`. Locale reset to `en_US` for this provider.
[2021-09-17 16:33:15,630]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.file` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:33:15,630]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.geo`.
[2021-09-17 16:33:15,632]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.geo`. Locale reset to `en_US` for this provider.
[2021-09-17 16:33:15,632]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.internet`.
[2021-09-17 16:33:15,638]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.internet` has been localized to `zh_CN`.
[2021-09-17 16:33:15,638]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.isbn` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:33:15,639]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.job`.
[2021-09-17 16:33:15,642]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.job` has been localized to `zh_CN`.
[2021-09-17 16:33:15,643]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.lorem`.
[2021-09-17 16:33:15,646]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.lorem` has been localized to `zh_CN`.
[2021-09-17 16:33:15,647]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.misc`.
[2021-09-17 16:33:15,648]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.misc`. Locale reset to `en_US` for this provider.
[2021-09-17 16:33:15,648]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.person`.
[2021-09-17 16:33:15,656]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.person` has been localized to `zh_CN`.
[2021-09-17 16:33:15,657]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.phone_number`.
[2021-09-17 16:33:15,665]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.phone_number` has been localized to `zh_CN`.
[2021-09-17 16:33:15,666]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.profile` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:33:15,666]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.python` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:33:15,666]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.ssn`.
[2021-09-17 16:33:15,672]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.ssn` has been localized to `zh_CN`.
[2021-09-17 16:33:15,675]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.user_agent` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:33:15,675]-[login.py|__init__]-[line|67]-DEBUG   : 登录环境--->test
[2021-09-17 16:33:15,675]-[sendRequests.py|send_requests]-[line|97]-DEBUG   : 
请求方式: post
请求URL: https://gcgateway-dev.dingyl.com/unify_users/user/get/phone/code
请求data: {"n": {"out_organ_id": "dinge1e0bb139cd52aa335c2f4657eb6378f", "phone": "17205434095", "project_id": "hrm", "notice_title": 120}, "a": {"source": "1"}, "v": {}}
[2021-09-17 16:33:15,679]-[connectionpool.py|_new_conn]-[line|971]-DEBUG   : Starting new HTTPS connection (1): gcgateway-dev.dingyl.com:443
[2021-09-17 16:33:15,877]-[connectionpool.py|_make_request]-[line|452]-DEBUG   : https://gcgateway-dev.dingyl.com:443 "POST /unify_users/user/get/phone/code HTTP/1.1" 200 None
[2021-09-17 16:33:15,881]-[sendRequests.py|send_requests]-[line|112]-DEBUG   : 返回内容--->{'l': {'request_id': 'd69d70a5046b4f8e9212bfd1dd71db34'}, 'n': {'code_id': 'f6e50f52d7e34d5e8ecb06978d092095'}, 'r': {'message': '成功', 'result': '1', 'sub_code': '', 'sub_message': ''}}
[2021-09-17 16:33:15,884]-[login.py|is_true]-[line|109]-INFO    : 获取登录验证码成功
[2021-09-17 16:33:15,885]-[sendRequests.py|send_requests]-[line|97]-DEBUG   : 
请求方式: post
请求URL: http://121.40.151.38:9082/unify_users/notice/job/send/message
请求data: None
[2021-09-17 16:33:15,893]-[connectionpool.py|_new_conn]-[line|227]-DEBUG   : Starting new HTTP connection (1): 121.40.151.38:9082
[2021-09-17 16:33:16,014]-[connectionpool.py|_make_request]-[line|452]-DEBUG   : http://121.40.151.38:9082 "POST /unify_users/notice/job/send/message HTTP/1.1" 200 None
[2021-09-17 16:33:16,016]-[sendRequests.py|send_requests]-[line|112]-DEBUG   : 返回内容--->{'l': {'request_id': 'a158575096b547e38849de2601ce8cc2'}, 'r': {'message': '成功', 'result': '1', 'sub_code': '', 'sub_message': ''}}
[2021-09-17 16:33:16,017]-[login.py|is_true]-[line|109]-INFO    : 执行验证码发送任务成功
[2021-09-17 16:33:16,017]-[sendRequests.py|send_requests]-[line|97]-DEBUG   : 
请求方式: post
请求URL: https://gcgateway-dev.dingyl.com/unify_message/notice/message/query
请求data: {"n": {"user_name": "", "user_phone": "17205434095", "message_content": "", "send_type": "295"}, "a": {"source": "1284"}, "v": {}, "f": {"indexpage": 1, "repaging": "1", "pagesize": 10}}
[2021-09-17 16:33:16,025]-[connectionpool.py|_new_conn]-[line|971]-DEBUG   : Starting new HTTPS connection (1): gcgateway-dev.dingyl.com:443
[2021-09-17 16:33:16,129]-[connectionpool.py|_make_request]-[line|452]-DEBUG   : https://gcgateway-dev.dingyl.com:443 "POST /unify_message/notice/message/query HTTP/1.1" 200 None
[2021-09-17 16:33:16,130]-[sendRequests.py|send_requests]-[line|112]-DEBUG   : 返回内容--->{'l': {'request_id': '4bc3b480406e4de49e81a182af780d22'}, 'r': {'message': 'session过期', 'result': '2', 'sub_all_message': '', 'sub_code': '', 'sub_message': ''}}
