[2021-09-17 16:48:39,863]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.address`.
[2021-09-17 16:48:39,871]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.address` has been localized to `zh_CN`.
[2021-09-17 16:48:39,873]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.automotive`.
[2021-09-17 16:48:39,877]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.automotive`. Locale reset to `en_US` for this provider.
[2021-09-17 16:48:39,878]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.bank`.
[2021-09-17 16:48:39,881]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
[2021-09-17 16:48:39,882]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.barcode`.
[2021-09-17 16:48:39,883]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.barcode`. Locale reset to `en_US` for this provider.
[2021-09-17 16:48:39,885]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.color`.
[2021-09-17 16:48:39,887]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.color`. Locale reset to `en_US` for this provider.
[2021-09-17 16:48:39,888]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.company`.
[2021-09-17 16:48:39,893]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.company` has been localized to `zh_CN`.
[2021-09-17 16:48:39,894]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.credit_card`.
[2021-09-17 16:48:39,895]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.credit_card`. Locale reset to `en_US` for this provider.
[2021-09-17 16:48:39,896]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.currency`.
[2021-09-17 16:48:39,898]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.currency`. Locale reset to `en_US` for this provider.
[2021-09-17 16:48:39,899]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.date_time`.
[2021-09-17 16:48:39,903]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.date_time`. Locale reset to `en_US` for this provider.
[2021-09-17 16:48:39,904]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.file` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:48:39,904]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.geo`.
[2021-09-17 16:48:39,906]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.geo`. Locale reset to `en_US` for this provider.
[2021-09-17 16:48:39,906]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.internet`.
[2021-09-17 16:48:39,912]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.internet` has been localized to `zh_CN`.
[2021-09-17 16:48:39,913]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.isbn` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:48:39,913]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.job`.
[2021-09-17 16:48:39,917]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.job` has been localized to `zh_CN`.
[2021-09-17 16:48:39,918]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.lorem`.
[2021-09-17 16:48:39,921]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.lorem` has been localized to `zh_CN`.
[2021-09-17 16:48:39,922]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.misc`.
[2021-09-17 16:48:39,923]-[factory.py|_find_provider_class]-[line|101]-DEBUG   : Specified locale `zh_CN` is not available for provider `faker.providers.misc`. Locale reset to `en_US` for this provider.
[2021-09-17 16:48:39,923]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.person`.
[2021-09-17 16:48:39,932]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.person` has been localized to `zh_CN`.
[2021-09-17 16:48:39,933]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.phone_number`.
[2021-09-17 16:48:39,941]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.phone_number` has been localized to `zh_CN`.
[2021-09-17 16:48:39,942]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.profile` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:48:39,942]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.python` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:48:39,942]-[factory.py|_find_provider_class]-[line|94]-DEBUG   : Looking for locale `zh_CN` in provider `faker.providers.ssn`.
[2021-09-17 16:48:39,949]-[factory.py|_find_provider_class]-[line|106]-DEBUG   : Provider `faker.providers.ssn` has been localized to `zh_CN`.
[2021-09-17 16:48:39,951]-[factory.py|_find_provider_class]-[line|113]-DEBUG   : Provider `faker.providers.user_agent` does not feature localization. Specified locale `zh_CN` is not utilized for this provider.
[2021-09-17 16:48:39,951]-[login.py|__init__]-[line|66]-DEBUG   : 登录环境--->test
[2021-09-17 16:48:39,952]-[sendRequests.py|send_requests]-[line|97]-DEBUG   : 
请求方式: post
请求URL: https://gcgateway-dev.dingyl.com/unify_users/user/get/phone/code
请求data: {"n": {"out_organ_id": "dinge1e0bb139cd52aa335c2f4657eb6378f", "phone": "17205434095", "project_id": "hrm", "notice_title": 120}, "a": {"source": "1"}, "v": {}}
[2021-09-17 16:48:39,956]-[connectionpool.py|_new_conn]-[line|971]-DEBUG   : Starting new HTTPS connection (1): gcgateway-dev.dingyl.com:443
[2021-09-17 16:48:40,150]-[connectionpool.py|_make_request]-[line|452]-DEBUG   : https://gcgateway-dev.dingyl.com:443 "POST /unify_users/user/get/phone/code HTTP/1.1" 200 None
[2021-09-17 16:48:40,154]-[sendRequests.py|send_requests]-[line|112]-DEBUG   : 返回内容--->{'l': {'request_id': 'ed1473e99e054cd38cc6a7abb9c5257b'}, 'n': {'code_id': '372d8bf048bd4359901facebd0fca731'}, 'r': {'message': '成功', 'result': '1', 'sub_code': '', 'sub_message': ''}}
[2021-09-17 16:48:40,158]-[login.py|is_true]-[line|112]-INFO    : 获取登录验证码成功
[2021-09-17 16:48:40,158]-[sendRequests.py|send_requests]-[line|97]-DEBUG   : 
请求方式: post
请求URL: http://121.40.151.38:9082/unify_users/notice/job/send/message
请求data: None
[2021-09-17 16:48:40,166]-[connectionpool.py|_new_conn]-[line|227]-DEBUG   : Starting new HTTP connection (1): 121.40.151.38:9082
[2021-09-17 16:48:40,279]-[connectionpool.py|_make_request]-[line|452]-DEBUG   : http://121.40.151.38:9082 "POST /unify_users/notice/job/send/message HTTP/1.1" 200 None
[2021-09-17 16:48:40,282]-[sendRequests.py|send_requests]-[line|112]-DEBUG   : 返回内容--->{'l': {'request_id': '48696dc67a24418b9f16c927c37f4df0'}, 'r': {'message': '成功', 'result': '1', 'sub_code': '', 'sub_message': ''}}
[2021-09-17 16:48:40,282]-[login.py|is_true]-[line|112]-INFO    : 执行验证码发送任务成功
[2021-09-17 16:48:40,283]-[sendRequests.py|send_requests]-[line|97]-DEBUG   : 
请求方式: post
请求URL: https://gcgateway-dev.dingyl.com/unify_message/notice/message/query
请求data: {"n": {"user_name": "", "user_phone": "17205434095", "message_content": "", "send_type": "295"}, "a": {"source": "1284"}, "v": null, "f": {"indexpage": 1, "repaging": "1", "pagesize": 10}}
[2021-09-17 16:48:40,290]-[connectionpool.py|_new_conn]-[line|971]-DEBUG   : Starting new HTTPS connection (1): gcgateway-dev.dingyl.com:443
[2021-09-17 16:48:40,402]-[connectionpool.py|_make_request]-[line|452]-DEBUG   : https://gcgateway-dev.dingyl.com:443 "POST /unify_message/notice/message/query HTTP/1.1" 200 None
[2021-09-17 16:48:40,405]-[sendRequests.py|send_requests]-[line|112]-DEBUG   : 返回内容--->{'l': {'request_id': '6835c20fca1a4ce2be3fc78a0805f068'}, 'r': {'message': 'session过期', 'result': '2', 'sub_all_message': '', 'sub_code': '', 'sub_message': ''}}
